apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zapper-webapp
  template:
    metadata:
      labels:
        app: zapper-webapp
    spec:
      nodeSelector:
        type: mongoer
      containers:
      - name: webapp-container
        image: masep01/zapper-web:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: registry-secret
