apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: zapper-webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32333
